name: "Roberto Efraín Díaz"
description: "This is the official web page for Roberto Efraín Díaz."

url: "http://rediaz.science"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
  advocacy:
          output: true
  cv:
          output: true
  media:
          output: true
  publications:
          output: true
