name: "Roberto Efraín Díaz"
description: "This is the official web page for Roberto Efraín Díaz at UCSF."

url: "http://rediaz.science"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
